Name         : kf5-kconfigwidgets
Version      : 4.99.0
Release      : 1
Group        : System/Base
License      : GPLv2+
Summary      : KDE Frameworks 5 Tier 3 addon for creating configuration dialogs
Description  : |
  KConfigWidgets provides easy-to-use classes to create configuration dialogs, as
  well as a set of widgets which uses KConfig to store their settings.
URL          : http://www.kde.org
SetupOptions : -q -n %{name}-%{version}/upstream

Sources:
    - "%{name}-%{version}.tar.xz"

RpmLintIgnore:
    - devel-file-in-non-devel-package
    - no-changelogname-tag
    - library-without-ldconfig-postin
    - library-without-ldconfig-postun

Configure    : none
Builder      : none

PkgBR:
    - kf5-rpm-macros
    - extra-cmake-modules
    - qt5-tools
    - kf5-kauth-devel
    - kf5-kcoreaddons-devel
    - kf5-kcodecs-devel
    - kf5-kconfig-devel
    - kf5-kconfig-gui
    - kf5-kdoctools-devel
    - kf5-kguiaddons-devel
    - kf5-ki18n-devel
    - kf5-kwidgetsaddons-devel
    - gettext-devel
PkgConfigBR:
    - Qt5Core
    - Qt5DBus
    - Qt5Xml
    - Qt5Network
    - Qt5Gui
    - Qt5Widgets
    - Qt5Concurrent
    - Qt5Test
    - Qt5Script
Requires:
    - kf5-filesystem

RequiresPost:
    - /sbin/ldconfig
RequiresPostUn:
    - /sbin/ldconfig

Files:
    - "%doc COPYING COPYING.LIB README.md"
    - "%{_kf5_libdir}/libKF5ConfigWidgets.so.*"
    - "%{_kf5_bindir}/preparetips5"
    - "%{_kf5_datadir}/kf5/kconfigwidgets"
    - "%{_kf5_mandir}/man1/*"

SubPackages:
    - Name: devel
      Group: Development/Libraries
      Summary: Development files for %{name}
      Description: |
        The %{name}-devel package contains the files necessary to develop applications |
        that use %{name}.
      Requires:
          - kf5-kauth-devel
          - kf5-kcoreaddons-devel
          - kf5-kcodecs-devel
          - kf5-kconfig-devel
          - kf5-kconfig-gui
          - kf5-kdoctools-devel
          - kf5-kguiaddons-devel
          - kf5-ki18n-devel
          - kf5-kwidgetsaddons-devel
      Files:
          - "%{_kf5_includedir}/kconfigwidgets_version.h"
          - "%{_kf5_includedir}/KConfigWidgets"
          - "%{_kf5_libdir}/libKF5ConfigWidgets.so"
          - "%{_kf5_libdir}/cmake/KF5ConfigWidgets"
          - "%{_datadir}/qt5/mkspecs/modules/qt_KConfigWidgets.pri"
